spring.application.name=serenamente

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/serenamente}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
app.database.create-if-missing=${DB_CREATE_IF_MISSING:true}

spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:none}
spring.jpa.open-in-view=false
